//! Auto-generated Burn models + build diagnostics.
//!
//! This module includes:
//! 1. `diagnostics.rs` — compile_error! macros if models are missing/broken
//!    (in strict mode). In dev mode this file is empty.
//! 2. Model code generated by burn-onnx from ONNX files.

// ── Build diagnostics (compile errors for missing/broken models) ────────────
// In strict mode (default), this file contains compile_error!() calls that
// stop the build with clear instructions. In dev mode (--features dev),
// this file is empty and the build proceeds with fallbacks.
include!(concat!(env!("OUT_DIR"), "/model/diagnostics.rs"));

// ── Silero VAD (generated from silero_vad.onnx) ────────────────────────────
#[cfg(has_silero_vad)]
pub mod silero_vad {
    include!(concat!(env!("OUT_DIR"), "/model/silero_vad.rs"));
}

// ── ECAPA-TDNN (generated from ecapa_tdnn.onnx) ────────────────────────────
#[cfg(has_ecapa_tdnn)]
pub mod ecapa_tdnn {
    include!(concat!(env!("OUT_DIR"), "/model/ecapa_tdnn.rs"));
}
